image:
  file: .gitpod.Dockerfile

tasks:
  - command: echo "Terminal lista para compilar"

vscode:
  extensions:
    - ms-vscode.cpptools

github:
  prebuilds:
    master:
      addCheck: true
      init: echo "Prebuild todo listo"
